esphome:
  name: esp32test
  friendly_name: esp32test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  reboot_timeout: 15min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Test"
    password: "Esp32Test"

captive_portal:

web_server:
 port: 80

sensor:
 - platform: internal_temperature
   name: "Internal Temperature"


switch:
  - id: relais_b
    platform: gpio
    pin: GPIO27
    name: "B-relais"

  - platform: gpio
    pin: GPIO22
    name: "22_blue-led"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: "G_switch"
    on_press: 
      then:
        - switch.toggle: relais_b
